title: 'Les Fermes Solaires du Mont-Valérien'
default_lang: fr
author:
  name: 'Joe Bloggs'
  email: contact@fsmv.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
