title: FSMV
default_lang: fr
author:
  name: null
  email: philippe.lakas@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
